### PR TITLE
Update rules/off_topic/rules.markdown

### PR DESCRIPTION
**Pull request by geluk**
Maybe add the rule "No video-related threads"? It's only listed in the chat thread at the moment, so I don't think many people will know of its existence.

### CODE REVIEW

**Comment by shrink** [comment]
Why are video threads banned?

**Comment by shrink** [comment]
May be worth clarifying, that rule reads as if it's saying "threads about videos aren't allowed, post all videos in the chat thread".

**Comment by DanielleStarr** [comment]
SYC is only for Minecraft videos. I dont want other WONDERFUL BUT NOT RELEVANT CONTENT there!

**Comment by Cuuldude** [comment]
They were never allowed because they're spammy. OMG LOL LOOK AT THIS VID I FOUND is pointless.

**Comment by shrink** [comment]
right sure SPAM videos (like "herp derp watch this video of some korean guy dance lol") are bad, but a blanket ban on all videos seems weird. Although I don't check OT much...

**Comment by geluk** [comment]
Citricsquid, that was not what I meant (I don't think I conveyed the message very well. My fault) The rule is supposed to be about, as Cuuldude said "omg look at this random video I found on the internet" posts/threads. Threads like that show up every once in a while, while these should really be posted in the chat thread. Especially since the "post your videos here" thread (I can't recall it's exact name) was 'merged' into the chat thread when the chat thread was restarted.

**Comment by Cuuldude** [comment]
If someone has made a video they want to show off, it can go in the User Creations subforum of CMA.

And yeah, as bagger said, we've always used the chat thread as the video discussion bin.

I'd be happy to allow them, if they have a certain amount of discussion value. Would be difficult to differentiate between what's acceptable or not, though.

**Pull request closed without merging**
