### PR TITLE
Stop IRC impersonation and the discouragement of players towards specific server.

### PR DESCRIPTION
**Pull request by SSederberg**

### CODE REVIEW

**Comment by JefeCC** [comment]
wasn't this closed once already?

**Comment by DanielHarman** [comment]
It was closed because Miner had a outdated branch of the rules.

**Comment by CoderPluto** [comment]
Doesn't the discouragement of players joining servers basically ruin negative reviews? Sometimes people post negative reviews about the server (They do the same for hosts) because they had bad experiences or had a bad time.

**Comment by LordRalex** [comment]
This server rule change is very badly worded. What is the point of it? What problem is there that this is solving?

The irc rule change seems bloated in the wording.

**Comment by LordRalex** [comment]
In favor of https://github.com/minecraftforum/rules/pull/171 for the change, as it handles the IRC bit directly, instead of trying to apply another rule change as well.

**Pull request closed without merging**
