### PR TITLE
Clarify this rule a bit more for infraction purposes.

### PR DESCRIPTION
**Pull request by DaneEveritt**
There has been a notable uptick of people who go around the hosting section solely to discredit hosts and cause arguments. Hopefully this can help put that to a stop since it goes nowhere productive in most cases.

### CODE REVIEW

**Comment by LordRalex** [comment]
Why not use the existing don't start arguments? 

And what kind of posts are influencing this?

**Comment by DaneEveritt** [comment]
I'm seeing a lot of posts that are just people finding flaws in a hosts topic, formatting issues, dislike of a theme the hot is using, server specs, etc. that people will ask questions about in an apparent attempt to discredit the host.

I can link you in IRC some specific posts. I was thinking this rule would help to keep that section about hosting related things, not just people bashing a host for their choice of theme or whatnot.

**Comment by LordRalex** [comment]
If it is only one post, what is really so bad? Unless they are making entire stream of posts to just degrade, then what is really that bad?

In any case, the wording of the rule change is vague and literary says only x, y, and z are allowed. That is not a way to tackle the issue.

**Comment by DaneEveritt** [comment]
Fair enough. Closing this for now since this issue was related to a previous troublesome user.

**Pull request closed without merging**
