### PR TITLE
Update rules.markdown

### PR DESCRIPTION
**Pull request by Vauff**
Make it clear server threads are not to be posted in Looking For. Also fixed grammar issue.

### CODE REVIEW

**Comment by LordRalex** [comment]
Isn't this just what 
`Only threads looking for specific servers, staff members, builders, or ideas are allowed` 
is about

**Comment by Vauff** [comment]
I don't think it's clear enough and especially since this is a very common thing in Looking For. The more clear the better.

**Comment by LordRalex** [comment]
Then it should be appended to the existing rule, or clarified there. Having it be in 2 places for the same thing is bad

**Comment by Vauff** [comment]
I looked over it and decided it would be better that way, updated it :)

**Pull request merged**
