### PR TITLE
You don't want a prolonged suspension, do you?

### PR DESCRIPTION
**Pull request by lovettbp**
Grammar and spelling adjustments, make it clear to users that continuing to violate the same rule(s) is going to get them a prolonged suspension. Maybe this will help prevent _some_ rulebreaking. Not going to add the lee-way for this because then they'll just think they're in the safe zone after 3 months.

Would like some feedback on this. It's already in the staff guidelines, I thought we should add it here so people don't ask why they got a 3 point or complain about how there's nothing in the rules that states we can give them a 3 point for a minor violation.

### CODE REVIEW

**Comment by LordRalex** [comment]
This really is not something that needs to be in the rules. The don't break multiple is what moderators are suppose to do, it is not really a rule. Even then, it makes no sense to just have it in servers.

The formatting fixes are fine, but the rule does not needed to be added.

**Comment by Vauff** [comment]
I still think we should keep that information about ignoring infractions but it should be moved to somewhere in here http://rules.mcf.li/#global-guidelines:infractions

**Comment by lovettbp** [comment]
The problem with that is that this does not apply to all sections. This is a section-specific thing. 

I can totally see where you're coming from though Ralex. I just thought it might discourage people from ignoring it a bit more because they'd be wary of getting a 3 point. If you don't want it, that's fine, completely understandable.

**Comment by LordRalex** [comment]
Something like "if you ignore, we 2 point you" is inaccurate in many ways, and is only specific to servers because of how mods in there are suppose to be. We should not though be saying ignoring them in servers is worse than ignoring it in off topic. That is bad policy.

Such a rule should either be for all, or for none to the user.

**Comment by lovettbp** [comment]
I have removed the section about the points. This is ready to be merged now.

**Pull request merged**
