### PR TITLE
Update rules.markdown

### PR DESCRIPTION
**Pull request by Vauff**
When people request a specific server people can't just reply with an IP, they must give information about the server.

### CODE REVIEW

**Comment by Vauff** [comment]
Basically I've seen some people in Looking For just posting their server IP in somebody's topic when they are looking for a server. I realized this rule didn't exactly mention server IP's in it. The main point of it is the rule said you couldn't post "www.mywebsitehere.com" but not anything about server IP's just being "play.myserverhere.net". This PR adds on to it saying you can't do it with server IP's either.

**Comment by shrink** [comment]
I'm specifically talking about the phrasing, it doesn't make sense.

**Comment by Vauff** [comment]
Do you think "link or IP" would be better then "link/IP" then?

**Comment by DanielHarman** [comment]
"they cannot just provide a link/IP"
A link can work with IPs, this line is redundant.

"to a topic/site/server"
Linking servers is covered by "link to topic/site" and this line "do not post PC server threads".

**Comment by Vauff** [comment]
Nimphina I mean when somebody requests a server to play on, not server topics as those obviously belong in PC servers. I kind of forgot about this pull request so I'm just going to edit it from what I've seen in the comments here and we'll see what happens.

**Comment by LordRalex** [comment]
Seems better now, giving my stamp of approval

**Pull request merged**
