### PR TITLE
Rules rearrangement.

### PR DESCRIPTION
**Pull request by ThePastmaster**
I think this would serve better as a global rule. (Former GM and MG, now) MD received a ton of these every once in a while and as such not just a Support Sectional Rule.

### CODE REVIEW

**Comment by shrink** [comment]
Do people frequently post ban lists outside of the servers section? Do you have any examples?

**Comment by ThePastmaster** [comment]
Search is giving me some attitude. I haven't seen any examples recently (Read: Last few weeks) but I have seen them a few times. It's almost seasonal. If one pops up then there's a load more coming after. Then it's silent for a month or more before the next batch. Continuing my search for clear cut blacklist threads outside of support.

**Comment by LordRalex** [comment]
the only section that would see it would be MD out of really any section. MnM, SYC, OT, PE would most likely not, 360 might. I would say it is not common enough though.

**Comment by ThePastmaster** [comment]
No-matter where it's posted really, it's going to be a nuisance. Hell General Gaming could use one too if someone posts a "Oh I was playing X and he did 1, 2, 3 his name is ABC so watch out." thing. Though I think that would more go under personal security or something now that I think about it. Bad-ish example. >_<

**Comment by shrink** [comment]
generally I want to keep the least amount of rules possible, if we don't ABSOLUTELY NEED to have a rule then we shouldn't have it, that way we can rely on MOST users seeing the rules and thinking "oh they're pretty short, I'll read them all". If we start adding rules that are _sometimes_ relevant or _sometimes_ an issue we'll end up with an overwhelming amount. 

Although if we don't allow banlists it really should be noted somewhere; even if it isn't the primary rules. I wonder if we should maybe expand the rules into 2 sections, "guidelines" (eg: don't use profanity) and "restrictions" (eg: no banlists) that way users can easily understand a general idea of how the forum works from guidelines and then when making a topic they can view the restrictions. 

hmm.

**Comment by ThePastmaster** [comment]
Hey, sounds awesome when you bring it up. :D Will nest on it and think and ponder. ^_^

**Pull request closed without merging**
