### PR TITLE
Add a rule to not quote lengthy OPs

### PR DESCRIPTION
**Pull request by Vazkii**
Quoting big OPs has been a problem for a while, I hate it, and I'm sure I'm not the only one that does so, when someone quotes a massive OP just to say "cool mod" or something. This rule tries to stop that.

### CODE REVIEW

**Comment by AtomicStryker** [comment]
Honestly they should just change the forum code to not allow quotes exceeding x length, or atleast automatically hiding those

**Comment by shrink** [comment]
Vazkii:

This is a good idea, however I think it would benefit from positive framing and making it relevant to _all_ posts. For example something like: 

> Quoting relevant portions of other users posts is a good way to foster discussion, members will be notified when their posts are quoted. Quoting entire posts is discouraged, especially if they are long, delete the parts that are not relevant to your post.

Although I suspect the majority of people that do this (quote the entire opening post or another post) do it because they think "quote" is the only way to reply and they don't realise they can highlight and delete the quote from the post box. This seems like an issue that wouldn't benefit from a rule change; the sort of people that read through the rules are not the sort of people this affects.

Can you link to a couple of example posts so I can see what sort of people are doing this and if I can work out a better way to approach a solution to this.

Thanks for the contribution by the way :+1:

**Comment by shrink** [comment]
AtomicStryker: 

> Honestly they should just change the forum code to not allow quotes exceeding x length, or atleast automatically hiding those

That would require modifying the IPB core, something the development team is reluctant to do unless absolutely required and I don't think this warrants it, although if we can't work out a better solution to the problem I will consider requesting it.

**Comment by Vazkii** [comment]
Sure, here's an example from the mine and blade battlegear thread: http://www.minecraftforum.net/topic/895339-125-forge-mine-blade-battlegear/page__st__5640#entry16657455

**Pull request closed without merging**
